# Regresion y correlacion


`Cristian Camilo Hernandez y David Esteban Lasso Herrera`


**Contexto del conjunto de datos**

Los terremotos son un fenomeno que se viven dia a dia en todo el mundo . . .

## Referencia de la base de datos

**Keser, Mustafa.** (2023). *Earthquakes 2023 Global* [Conjunto de datos].
Kaggle.  
Disponible en:
 [https://www.kaggle.com/datasets/mustafakeser4/earthquakes-2023-global](https://www.kaggle.com/datasets/mustafakeser4/earthquakes-2023-global)

## Variables de dataset y explicacion de algunas de ellas relevantes

| **Columna**   | **Descripción breve** |
|----------------|------------------------|
| **title** | Título o descripción del evento sísmico, este combina la magnitud y ubicación|
| **magnitude** | Valor numérico en la escala richter de la magnitud que se produjo. |
| **date_time** | Fecha  y hora exacta del evento en formato UTC. |
| **cdi** | *Community Determined Intensity*: intensidad percibida por las personas (escala 1–10) |
| **mmi** | *Modified Mercalli Intensity*: intensidad medida instrumentalmente (daños observables). |
| **alert** | Nivel de alerta emitido (verde, amarillo, naranja, rojo)|
| **tsunami** | Indicador binario (0/1) que señala si el sismo generó o pudo generar un tsunami. |
| **sig** | *Significance index*: número que resume la “importancia” del evento según magnitud, profundidad y reportes. |
| **net** | Red sísmica que detectó el evento  |
| **nst** | Número de estaciones sísmicas |
| **dmin** | Distancia mínima (en grados) a la estación más cercana que registró el sismo. |
| **gap** | Azimutal gap (en grados): medida de la cobertura angular de estaciones; valores bajos indican mejor precisión. |
| **magType** | Tipo de magnitud usada  *mb*, *Mw*, *ML*, *Md*. |
| **depth** | Profundidad del hipocentro en kilómetros bajo la superficie. |
| **latitude** | Latitud geográfica del epicentro  |
| **longitude** | Longitud geográfica del epicentro. |
| **location** | Lugar en la que se produjo el terremoto |
| **continent** | Continente del epicentro|
| **country** | País del epicentro  |

*Objetivo* --> Crear un modelo de regresion lineal multiple en un plano R3 para predecir la magnitud dadas algunas variables indepedientes predictoras

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset_eartquake = pd.read_csv('earthquake_data.csv')

dataset_eartquake

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,NaN
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,green,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,Fiji
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,NaN
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,green,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,13-01-2001 17:33,0,8,NaN,0,912,us,427,0.000,0.0,mwc,60.000,13.0490,-88.660,"Puerto El Triunfo, El Salvador",NaN,NaN
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,10-01-2001 16:02,5,7,NaN,0,745,ak,0,0.000,0.0,mw,36.400,56.7744,-153.281,"Old Harbor, Alaska",North America,NaN
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,09-01-2001 16:49,0,7,NaN,0,776,us,372,0.000,0.0,mwb,103.000,-14.9280,167.170,"Port-Olry, Vanuatu",NaN,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,01-01-2001 08:54,0,5,NaN,0,711,us,64,0.000,0.0,mwc,33.000,6.6310,126.899,"Mindanao, Philippines",NaN,NaN
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,01-01-2001 06:57,0,7,NaN,0,865,us,324,0.000,0.0,mwc,33.000,6.8980,126.579,"Lukatan, Philippines",NaN,Philippines

In [2]:
dataset_eartquake.columns

Index(['title', 'magnitude', 'date_time', 'cdi', 'mmi', 'alert', 'tsunami',
       'sig', 'net', 'nst', 'dmin', 'gap', 'magType', 'depth', 'latitude',
       'longitude', 'location', 'continent', 'country'],
      dtype='object')

Existen varias columnas que para nuestro caso no seran necesarias en la regresion multiple sea por su tipologia o por el uso que se les puede brindar

In [3]:
dataset_eartquake.drop(
    columns=['date_time', 'alert', 'net','magType', 'latitude', 'longitude'] , inplace=True , axis=1 
)

In [4]:
dataset_eartquake

,title,magnitude,cdi,mmi,tsunami,sig,nst,dmin,gap,depth,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,8,7,1,768,117,0.509,17.0,14.000,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,4,4,0,735,99,2.229,34.0,25.000,"Bengkulu, Indonesia",NaN,NaN
2,M 7.0 -,7.0,3,3,1,755,147,3.125,18.0,579.000,NaN,Oceania,Fiji
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,5,5,1,833,149,1.865,21.0,37.000,"Neiafu, Tonga",NaN,NaN
4,M 6.6 -,6.6,0,2,1,670,131,4.998,27.0,624.464,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,0,8,0,912,427,0.000,0.0,60.000,"Puerto El Triunfo, El Salvador",NaN,NaN
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,5,7,0,745,0,0.000,0.0,36.400,"Old Harbor, Alaska",North America,NaN
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,0,7,0,776,372,0.000,0.0,103.000,"Port-Olry, Vanuatu",NaN,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,0,5,0,711,64,0.000,0.0,33.000,"Mindanao, Philippines",NaN,NaN
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,0,7,0,865,324,0.000,0.0,33.000,"Lukatan, Philippines",NaN,Philippines

Ahora vamos a comprobar cuales seran las posibles variables predictoras para crear el modelo y cuales tienen mayor correlacion con la magnitud de un terremoto

In [5]:
possibly_columns = dataset_eartquake.drop(columns=['title','location','continent','country','magnitude']).columns.values

correlation_dataframe = pd.DataFrame(
    {'column_name': possibly_columns,
     'correlation_magnitude': [i for i in range(1, len(possibly_columns)+1)]}
)

def get_correlation_variables():
    correlation_list = []
    
    for column in possibly_columns:
        correlation = dataset_eartquake[column].corr(dataset_eartquake['magnitude'])
        correlation_list.append(correlation)
    
    correlation_dataframe['correlation_magnitude'] = correlation_list
    
    return correlation_dataframe

correlation_result = get_correlation_variables()

correlation_dataframe

  column_name  correlation_magnitude
0         cdi               0.209549
1         mmi               0.285552
2     tsunami              -0.004726
3         sig               0.515871
4         nst               0.113114
5        dmin              -0.091403
6         gap              -0.110626
7       depth               0.030644

 Con esto ya evidenciamos el estado de las variables y como es la correlacion con la magnitud que sera lo que vamos a predecir , notamos que existen algunas con una correlacion muy baja o otras totalmente negativa. en este caso utilizaremos 3 variables de tipo indepediente para crear el modelo de Regresion lineal multiple

 
 
 **Variable independiente**


| Variable | Tipo | Descripción |
|-----------|------|-------------|
| **CDI** | Cuantitativa | *Community Determined Intensity*: intensidad percibida por las personas |
| **MMI** | Cuantitativa | *Modified Mercalli Intensity*: intensidad medida instrumentalmente. |
| **Tsunami** | Cualitativa (Binaria) | 1 = el sismo generó tsunami; 0 = no lo generó. |

---

 **Variable dependiente**

| Variable | Tipo |
|-----------|------|
| **Magnitud** | Cuantitativa (Predictora) |


---

In [6]:
dataset_regression = dataset_eartquake[['title' , 'location', 'cdi', 'mmi' , 'tsunami', 'magnitude']]

dataset_regression

,title,location,cdi,mmi,tsunami,magnitude
0,"M 7.0 - 18 km SW of Malango, Solomon Islands","Malango, Solomon Islands",8,7,1,7.0
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia","Bengkulu, Indonesia",4,4,0,6.9
2,M 7.0 -,NaN,3,3,1,7.0
3,"M 7.3 - 205 km ESE of Neiafu, Tonga","Neiafu, Tonga",5,5,1,7.3
4,M 6.6 -,NaN,0,2,1,6.6
...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...","Puerto El Triunfo, El Salvador",0,8,0,7.7
778,"M 6.9 - 47 km S of Old Harbor, Alaska","Old Harbor, Alaska",5,7,0,6.9
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu","Port-Olry, Vanuatu",0,7,0,7.1
780,"M 6.8 - Mindanao, Philippines","Mindanao, Philippines",0,5,0,6.8
781,"M 7.5 - 21 km SE of Lukatan, Philippines","Lukatan, Philippines",0,7,0,7.5

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

#Creamos las instancias para trabajar

scaler = StandardScaler()
regression_model = LinearRegression()

X = dataset_regression.drop(columns=['title','location','magnitude'])

Y = dataset_regression['magnitude'] 

#Aplicamos el escalador

X_scaled = scaler.fit_transform(X)

#Dividimos los datos en entrenamiento y prueba

x_train , x_test , y_train , y_test = train_test_split(X_scaled , Y , test_size=0.2 , random_state=42)

#Entrenamos el modelo

regression_model = LinearRegression()

regression_model

LinearRegression()

In [10]:
regression_model.fit(x_train , y_train)

LinearRegression()

In [14]:
regression_parameters = [regression_model.intercept_] + list(regression_model.coef_)

regression_parameters

print(f'El intercepto es {regression_parameters[0]}')

for coeficiente in range(1, len(regression_parameters)):
    print(f'El coeficiente {coeficiente} es {regression_parameters[coeficiente]}')

El intercepto es 6.960168665437302
El coeficiente 1 es 0.0632177703458195
El coeficiente 2 es 0.1039778463068929
El coeficiente 3 es 0.0007890627812118176

Con todo esto obtenemos nuestro modelo de regresion lineal multiple como

$$ Y= 0.063x_1 + 0.103x_2 + 0.0007x_3 + 6.96 $$

## Pruebas de bondad de ajuste para el R_2